language: node_js
node_js: --lts
before_script:
  - git config user.name "qiurenbo"
  - git config user.email "qiurenbo@outlook.com"
  - sed -i'' "s~https://github.com/qiurenbo/blog.git~https://${access_token}@github.com/qiurenbo/qiurenbo.github.io.git~" _config.yml
script:
  - hexo g
  - hexo d
